---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buckets.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - buckets
      - buckets/status
      - bucketrequirements
      - bucketrequirements/status
    verbs:
      - "*"
