---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machineinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - machineinstances
      - machineinstances/status
      - machineinstancerequirements
      - machineinstancerequirements/status
    verbs:
      - "*"
