---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlinstances.definitions.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - definitions.crossplane.io
    resources:
      - mysqlinstances
      - mysqlinstances/status
      - mysqlinstancerequirements
      - mysqlinstancerequirements/status
    verbs:
      - "*"
