---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nosqlinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - nosqlinstances
      - nosqlinstances/status
      - nosqlinstancerequirements
      - nosqlinstancerequirements/status
    verbs:
      - "*"
