---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - postgresqlinstances
      - postgresqlinstances/status
      - postgresqlinstancerequirements
      - postgresqlinstancerequirements/status
    verbs:
      - "*"
