---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisclusters.definitions.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - definitions.crossplane.io
    resources:
      - redisclusters
      - redisclusters/status
      - redisclusterrequirements
      - redisclusterrequirements/status
    verbs:
      - "*"
