---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: buckets.common.crossplane.io
spec:
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: Bucket
      listKind: BucketList
      plural: buckets
      singular: bucket
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: buckets.common.crossplane.io
spec:
  infrastructureDefinitionRef:
    name: buckets.common.crossplane.io
