---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: machineinstances.common.crossplane.io
spec:
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: MachineInstance
      listKind: MachineInstanceList
      plural: machineinstances
      singular: machineinstance
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: machineinstances.common.crossplane.io
spec:
  infrastructureDefinitionRef:
    name: machineinstances.common.crossplane.io
