---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: nosqlinstances.definitions.crossplane.io
spec:
  crdSpecTemplate:
    group: definitions.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: NoSQLInstance
      listKind: NoSQLInstanceList
      plural: nosqlinstances
      singular: nosqlinstance
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: nosqlinstances.definitions.crossplane.io
spec:
  infrastructureDefinitionRef:
    name: nosqlinstances.definitions.crossplane.io
