---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: redisclusters.common.crossplane.io
spec:
  connectionSecretKeys:
    - endpoint
    - password
    - port
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: RedisCluster
      listKind: RedisClusterList
      plural: redisclusters
      singular: rediscluster
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                description: Version specifies the desired Redis version.
                enum:
                  - "2.6"
                  - "2.8"
                  - "3.2"
                  - "4.0"
                  - "5.0"
                type: string
            required:
              - version
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: redisclusters.common.crossplane.io
spec:
  infrastructureDefinitionRef:
    name: redisclusters.common.crossplane.io
